version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: ./Docker/Dockerfile
    image: chats-service
    container_name: chats-service
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - /var/www/vendor

    networks:
      - default
      - backend

  io.ciya.chats:
    image: nginx:alpine
    container_name: chats-service-nginx
    restart: unless-stopped
    #ports:
      #- 2583:80
    volumes:
      - ./:/var/www
      - ./Docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - default
      - proxynet

  db:
    image: mysql
    container_name: chats-service-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    networks:
      - default
  redis:
      image: redis:alpine
      container_name: chats-redis
      restart: unless-stopped
      command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
      volumes:
      - ./data/redis:/data
      #ports:
      #  - 6379
      networks:
      - default    

networks:
  proxynet:
    external: true
    name: proxy_network
  backend:
    external: true
    name: backend_network