version: "3.7"
services:
  app:
    build:
      args:
        user: ciya-prod
        uid: 1000
      context: ./
      dockerfile: ./Docker/Dockerfile
    image: notifications-service
    container_name: notifications-service
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
     - ./vendor:/var/www/vendor
    networks:
      - default
      - backend


  io.ciya.notifications:
    image: nginx:alpine
    container_name: notifications-service-nginx
    restart: unless-stopped
    ports:
      - 2582:2582
    volumes:
      - ./:/var/www
      - ./Docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - default
      - proxynet
  db:
    image: mysql
    container_name: notications-service-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    networks:
      - default
  redis:
      image: redis:alpine
      container_name: notications-service-redis
      restart: unless-stopped
      command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
      volumes:
      - ./data/redis:/data 
      ports:
        - 6379
      networks:
       - default     

networks:
  proxynet:
    external: true
    name: proxy_network
  backend:
    external: true
    name: backend_network