version: "3.7"
services:
  app:
    build:
      args:
        user: root
        uid: 1000
      context: ./
      dockerfile: ./Docker/Dockerfile
    image: rides-service
    container_name: rides-service
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./vendor:/var/www/vendor
    networks:
      - default
      - backend



  io.ciya.rides:
    image: nginx:alpine
    container_name: rides-service-nginx
    restart: unless-stopped
    #ports:
      #- 2571:2571
    volumes:
      - ./:/var/www/
      - ./Docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - default
      - proxynet
  db:
    image: mysql
    container_name: rides-service-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    networks:
      - default
  redis:
      image: redis:alpine
      container_name: rides-service-redis
      restart: unless-stopped
      command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
      networks:
       - default    
  
networks:
  proxynet:
    external: false
    name: proxy_network
  backend:
    external: false
    name: backend_network  